name: Step 1- verify Application push Trigger

on:
  push:
    branches:
      - main

jobs:
  verify-push-trigger:
    name: verify Applicatio push Trigger
    runs-on: ubuntu-latest

    steps:
      - name: Confirmation
        run: |
          echo "Application repository push"
          echo "Repository: ${{ github.repository }}"
          echo "Branch: ${{ github.ref_name }}"
          echo "Commit SHA: ${{ github.sha }}"

  